### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by nicegreg** [PagodaGoods/pagodagoods.github.io#1]
Was hoping the video behavior could be something similar to this https://girlfriend.com/#1

**Comment by nicegreg** [comment]
Maybe more space where the product icons are (margin top and bottom between product). It would be ideal if these could do something interactive. Maybe they fly in as you scroll or something of that nature. Want the product area to feel "innovative".

**Comment by nicegreg** [comment]
Can we change body copy to Montserrat: https://fonts.google.com/specimen/Montserrat

**Comment by nicegreg** [comment]
Underline designing on product section

**Comment by nicegreg** [comment]
Style form field to match the height of the button. I originally had a box around it but maybe that is weird?

**Comment by nicegreg** [comment]
Update down arrow at the top landing area to be a small version of this arrow but pointing down [
<img width="149" alt="screen shot 2016-12-12 at 9 20 01 am" src="https://cloud.githubusercontent.com/assets/17886750/21102450/421a833a-c04c-11e6-81dc-37b1ceb7e297.png">
](url)

**Comment by marcusrelacion** [comment]
Will mark these as complete in their respective issues. The discussions can continue there as well! ( #2, #3, #4, #5, #6 )
